run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - staticcheck
    - misspell

linters-settings:
  misspell:
    locale: US

run:
  timeout: 5m
  modules-download-mode: mod
